using System;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Activation;
using System.ServiceModel.Web;

namespace Hackathon.Web
{
    [ServiceContract(Namespace = "")]
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    public class Services
    {
        // Add [WebGet] attribute to use HTTP GET
        [OperationContract]
        [WebGet(BodyStyle = WebMessageBodyStyle.Bare, ResponseFormat = WebMessageFormat.Json)]
        public DataObject[] GetData()
        {
            return RawData();
        }

        public class DataObject
        {
            public string Id { get; set; }
            public string Title { get; set; }
            public string Notes { get; set; }
            public string IsComplete { get; set; }
            public DateTime DueDate { get; set; }
        }

        private DataObject[] RawData()
        {
            return
                new[]
                {
                    new DataObject {Id = "0", Title = "Meatloaf salami beef", Notes = "T-bone beef biltong ribeye sausage chicken meatloaf sausage chuck flank tri-tip tenderloin andouille chicken beef biltong spare chicken jerky pig ground chicken corned salami tail ribs tail headcheese chicken salami biltong corned flank ribeye shank headcheese jowl salami chicken pork jerky pork ground short ground tenderloin chuck chicken brisket venison corned chuck andouille beef venison t-bone meatloaf rump hamburger short t-bone ribeye meatloaf fatback t-bone", IsComplete = "True", DueDate = DateTime.Parse("2014-06-02 00:00:00")},
                    new DataObject {Id = "1", Title = "Beef headcheese swine", Notes = "Jowl headcheese ribs shank chuck ball pancetta loin tenderloin tongue pork fatback cow andouille headcheese tenderloin pork chicken pork chicken headcheese drumstick ribeye swine ribs andouille strip salami tenderloin chicken bresaola pig tongue strip short hamburger ribeye sausage brisket drumstick headcheese ball ribs venison shankle tenderloin ham sausage brisket ham headcheese pork strip ham ham ground shankle rump", IsComplete = "False", DueDate = DateTime.Parse("2014-05-21 00:00:00")},
                    new DataObject {Id = "2", Title = "Pig jowl", Notes = "Spare bresaola fatback ribs andouille headcheese t-bone spare flank tenderloin corned bacon short tenderloin t-bone ball tri-tip pork tongue pastrami venison pig biltong sirloin beef jerky ground sausage ground fatback t-bone brisket tongue pork tri-tip salami headcheese ribs boudin ham cow drumstick headcheese", IsComplete = "True", DueDate = DateTime.Parse("2014-05-16 00:00:00")},
                    new DataObject {Id = "3", Title = "Ham sirloin", Notes = "Pork sirloin meatloaf flank ball fatback ground venison ribs shoulder andouille short boudin tongue bresaola tongue corned biltong headcheese loin pork flank ground cow ground shankle ribs tenderloin spare salami shank sausage meatball t-bone pig rump t-bone fatback short pancetta shankle ribs tail pork spare headcheese", IsComplete = "False", DueDate = DateTime.Parse("2014-05-30 00:00:00")},
                    new DataObject {Id = "4", Title = "Drumstick chuck boudin", Notes = "Fatback salami shank salami bresaola pork pork loin bresaola headcheese short strip fatback andouille bresaola beef bacon meatball t-bone beef meatloaf jerky biltong ribs bacon hamburger meatball chicken corned headcheese pancetta t-bone tri-tip boudin venison boudin tail ball salami short shankle pastrami chicken tenderloin drumstick pork t-bone ribs short boudin jowl rump boudin tri-tip biltong pig sirloin", IsComplete = "False", DueDate = DateTime.Parse("2014-05-26 00:00:00")},
                    new DataObject {Id = "5", Title = "Bacon beef", Notes = "Tenderloin shoulder pastrami short ham pig hamburger tongue bacon spare bresaola ball jerky tenderloin chicken short chicken tenderloin boudin drumstick ground sirloin tri-tip drumstick meatloaf tongue corned fatback brisket tongue pastrami meatball ball bacon ground swine ball hamburger pork shank drumstick andouille beef short hamburger pig spare corned chicken shank salami", IsComplete = "True", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "6", Title = "Bresaola t-bone", Notes = "Biltong ham pork flank andouille headcheese tri-tip bacon bacon tail short tail tenderloin pork shank brisket pig beef short beef shank pig headcheese beef t-bone beef pork loin pork t-bone pork ground ball pork tri-tip chicken t-bone pancetta ham pork pancetta short strip corned corned ham ham headcheese pig chicken ham bacon t-bone andouille corned cow short cow pork tenderloin pork", IsComplete = "False", DueDate = DateTime.Parse("2014-05-28 00:00:00")},
                    new DataObject {Id = "7", Title = "Pancetta biltong", Notes = "Fatback ham venison venison pork pork ribs ribs pork pancetta shoulder boudin rump ground pastrami tri-tip chicken strip beef spare short pastrami meatloaf sausage beef pastrami boudin andouille chicken boudin andouille pork andouille jerky chicken shoulder tail boudin beef ball short pork cow headcheese spare flank pork flank sirloin ball chuck shankle shoulder chuck", IsComplete = "False", DueDate = DateTime.Parse("2014-05-21 00:00:00")},
                    new DataObject {Id = "8", Title = "Shank shankle", Notes = "Chicken hamburger chicken tenderloin chuck short spare ham fatback spare pancetta t-bone drumstick brisket beef t-bone rump salami bacon chicken tail short beef corned chicken hamburger corned t-bone jowl ground chuck pork tenderloin sirloin chuck drumstick ham beef ball boudin spare ham ribs tail turkey ham tail pork chicken headcheese tongue brisket tail tongue drumstick tail", IsComplete = "True", DueDate = DateTime.Parse("2014-06-01 00:00:00")},
                    new DataObject {Id = "9", Title = "Flank meatball", Notes = "Ham boudin pork chuck ribs headcheese fatback beef venison beef ball pig beef fatback headcheese headcheese hamburger headcheese corned spare shankle beef corned chicken jerky loin shoulder tongue pork boudin strip andouille tri-tip ball pork bresaola spare biltong headcheese flank pancetta hamburger spare hamburger spare ham ball spare t-bone meatloaf bacon boudin boudin", IsComplete = "False", DueDate = DateTime.Parse("2014-06-06 00:00:00")},
                    new DataObject {Id = "10", Title = "Shoulder t-bone biltong", Notes = "Spare ball bacon ground beef beef chicken boudin shankle cow beef spare chicken salami venison drumstick drumstick pork pig brisket shank chicken headcheese beef salami tongue ground rump sirloin pastrami short swine ribs sausage biltong pancetta spare fatback cow pastrami ham bacon tri-tip venison ham pig spare ball biltong meatball ground venison turkey chuck ribeye pancetta corned ham beef ball ground biltong shank brisket jowl ball meatball", IsComplete = "False", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "11", Title = "Hamburger bacon", Notes = "Chicken beef pig ribeye chicken brisket tri-tip pork jerky venison meatball beef tri-tip headcheese beef hamburger tri-tip headcheese rump corned drumstick tenderloin ground tenderloin pork ribeye chuck drumstick venison strip boudin jowl sausage ribeye venison tri-tip t-bone t-bone strip bresaola andouille chuck ribs shoulder pork jerky shankle tri-tip pig drumstick fatback", IsComplete = "True", DueDate = DateTime.Parse("2014-05-17 00:00:00")},
                    new DataObject {Id = "12", Title = "Bacon headcheese", Notes = "Spare corned bresaola ball t-bone tail beef chuck ham chuck andouille pancetta meatloaf turkey flank swine fatback tri-tip corned sirloin corned chuck hamburger tongue pork bacon ribs beef fatback hamburger turkey andouille ball shank pork meatloaf ground ham ham ball tongue swine loin biltong pancetta cow pig ball headcheese andouille jowl meatloaf tenderloin pancetta chuck flank flank chicken hamburger boudin ham t-bone tenderloin drumstick t-bone", IsComplete = "False", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "13", Title = "Ribs pork spare", Notes = "Brisket bacon fatback pork headcheese meatloaf chicken pig spare boudin rump ribeye fatback chuck ground pork pig pig ball spare t-bone chuck chicken pork jowl ribs pastrami hamburger shank ham sausage strip pork drumstick ball bresaola bresaola beef corned pork ground chuck drumstick flank boudin ground headcheese shank flank chicken turkey ham tenderloin meatball fatback meatloaf cow t-bone flank short flank headcheese drumstick meatloaf", IsComplete = "False", DueDate = DateTime.Parse("2014-05-24 00:00:00")},
                    new DataObject {Id = "14", Title = "Pork tri-tip", Notes = "Corned pork hamburger ball tail salami chuck jerky ball biltong venison short bacon bacon tongue turkey bresaola chicken meatball pork pork shank fatback pork t-bone t-bone meatball salami hamburger ribs ribs ham pig jerky chicken ball salami pancetta shank meatloaf meatloaf beef", IsComplete = "True", DueDate = DateTime.Parse("2014-06-06 00:00:00")},
                    new DataObject {Id = "15", Title = "Bresaola pastrami", Notes = "Pork rump spare drumstick chicken ham meatball ham bacon tail fatback shoulder shoulder biltong sirloin jerky beef venison bresaola ball andouille tail headcheese venison tenderloin loin salami ham swine tail ham ribs jowl ribeye bacon ground headcheese shankle tail shank venison chicken shank drumstick salami cow salami swine corned venison swine short jerky hamburger", IsComplete = "True", DueDate = DateTime.Parse("2014-05-28 00:00:00")},
                    new DataObject {Id = "16", Title = "Tail meatball ribeye", Notes = "Meatloaf boudin pork headcheese ham ball tenderloin pig tenderloin ribeye meatloaf pastrami chicken short sirloin short bresaola salami headcheese salami tri-tip short jowl fatback sirloin strip chuck bacon spare sausage shankle beef headcheese sirloin chuck beef meatball loin tenderloin swine tri-tip chicken tri-tip chuck short cow boudin pork pastrami tenderloin venison ball shankle", IsComplete = "True", DueDate = DateTime.Parse("2014-05-31 00:00:00")},
                    new DataObject {Id = "17", Title = "Tenderloin biltong pork", Notes = "Pork spare pig ham beef biltong tongue meatball tongue venison beef bresaola ball andouille ground sirloin tongue beef short beef pork headcheese pancetta short tenderloin shankle pork bacon sirloin flank t-bone short ham boudin chicken pork tri-tip tail ground tenderloin short t-bone tenderloin shankle jowl salami pig sirloin pancetta turkey venison corned shankle pork", IsComplete = "False", DueDate = DateTime.Parse("2014-05-19 00:00:00")},
                    new DataObject {Id = "18", Title = "Swine ground", Notes = "Hamburger shoulder jowl meatloaf andouille corned short pig spare flank andouille hamburger pastrami chicken tri-tip spare hamburger short turkey t-bone ball beef brisket tri-tip tail pancetta ham biltong ham hamburger cow meatloaf pork andouille fatback beef t-bone bresaola cow corned ground chuck sirloin swine andouille bresaola", IsComplete = "True", DueDate = DateTime.Parse("2014-05-28 00:00:00")},
                    new DataObject {Id = "19", Title = "Pork andouille", Notes = "Meatball rump ribeye tail corned corned turkey meatloaf venison tenderloin tenderloin chuck andouille chicken ball chuck fatback flank short pancetta flank ground corned pig chuck andouille fatback pancetta meatloaf cow headcheese spare ribeye brisket tail tongue turkey strip brisket hamburger flank boudin brisket ground corned t-bone beef headcheese chuck t-bone sirloin fatback pork meatloaf ground chicken turkey tongue bresaola bresaola sausage biltong tail flank tri-tip", IsComplete = "True", DueDate = DateTime.Parse("2014-06-02 00:00:00")},
                    new DataObject {Id = "20", Title = "Turkey bacon", Notes = "Turkey ribeye brisket bacon shoulder andouille venison pig spare beef ground chuck shank cow t-bone pork turkey biltong tri-tip sirloin tri-tip bacon hamburger hamburger corned headcheese shank short meatball cow bresaola pork meatloaf tail venison bacon drumstick boudin cow ribs biltong", IsComplete = "False", DueDate = DateTime.Parse("2014-05-28 00:00:00")},
                    new DataObject {Id = "21", Title = "Andouille pork", Notes = "Biltong sirloin headcheese cow tail bresaola short shankle tongue ribeye ham ground beef tri-tip ground pastrami boudin pork beef short ground loin ribs ham ham ribs venison fatback chicken ground andouille fatback swine fatback tenderloin beef pastrami ham pancetta ham rump tail pork pancetta flank shank pork headcheese andouille tenderloin tri-tip chicken beef bacon beef corned pig cow venison pork", IsComplete = "True", DueDate = DateTime.Parse("2014-05-22 00:00:00")},
                    new DataObject {Id = "22", Title = "Fatback pancetta", Notes = "Ribs tenderloin beef andouille ground venison biltong salami ham brisket tenderloin pig sirloin bacon ham beef pork salami tail strip flank rump chuck ribeye loin bacon beef ground pork bacon t-bone drumstick ham headcheese turkey pork rump short ball pork pork loin sausage beef ham ball", IsComplete = "False", DueDate = DateTime.Parse("2014-05-16 00:00:00")},
                    new DataObject {Id = "23", Title = "Ball loin brisket", Notes = "Fatback drumstick boudin strip jerky bacon t-bone pork tenderloin pork brisket ribs loin tail shank chicken pancetta bresaola chuck shank boudin ribeye tri-tip meatloaf chuck andouille short tenderloin beef flank sausage bresaola ground shankle sirloin hamburger chuck short pig headcheese bresaola pork ball biltong boudin fatback ball jowl drumstick chicken andouille short tongue ham spare rump", IsComplete = "False", DueDate = DateTime.Parse("2014-05-17 00:00:00")},
                    new DataObject {Id = "24", Title = "Ham tenderloin", Notes = "Bacon jerky hamburger pork pork venison fatback swine ribs pork tri-tip ball jerky ham meatball bacon headcheese short bacon rump ribs chuck hamburger sirloin sirloin pancetta tail pancetta drumstick meatball corned chicken swine fatback bresaola tri-tip ribeye ground fatback short rump tenderloin venison chicken chuck corned pig shank beef venison shank sirloin tri-tip ball headcheese ball salami biltong", IsComplete = "False", DueDate = DateTime.Parse("2014-05-29 00:00:00")},
                    new DataObject {Id = "25", Title = "Beef brisket", Notes = "Ground meatloaf shankle venison beef swine brisket andouille spare brisket cow t-bone t-bone shank t-bone flank jowl headcheese spare spare headcheese biltong ground pig ground brisket flank t-bone biltong headcheese flank jowl swine beef bresaola ball tri-tip t-bone headcheese tenderloin beef headcheese salami flank ribs beef ball boudin corned chuck drumstick ribs tail chuck pork biltong spare ribeye flank corned headcheese meatloaf shoulder jerky tri-tip turkey meatloaf", IsComplete = "False", DueDate = DateTime.Parse("2014-05-15 00:00:00")},
                    new DataObject {Id = "26", Title = "Corned ribeye", Notes = "Ground pork tenderloin venison chicken jowl sausage fatback pig fatback pork salami bacon beef flank pig pork headcheese boudin meatloaf pastrami rump meatloaf pastrami cow tenderloin headcheese tail beef andouille strip corned short andouille beef tri-tip flank ribs salami rump spare chuck jowl fatback shank rump pig flank pork rump chicken venison pork strip pork hamburger pastrami biltong corned andouille ribeye spare ribs pork pancetta jerky", IsComplete = "True", DueDate = DateTime.Parse("2014-05-23 00:00:00")},
                    new DataObject {Id = "27", Title = "Pork shank loin", Notes = "Chicken tail beef beef loin corned short bacon sirloin cow ground ground headcheese jowl tongue loin meatloaf chicken corned swine ball pork rump loin tri-tip andouille ham meatloaf chuck spare hamburger salami pancetta headcheese beef pork tenderloin sausage flank boudin shankle biltong andouille chuck headcheese bacon chuck shoulder ball pig boudin ribeye beef cow pork turkey shank t-bone sirloin cow pork bacon", IsComplete = "False", DueDate = DateTime.Parse("2014-05-23 00:00:00")},
                    new DataObject {Id = "28", Title = "Pig short", Notes = "Drumstick pancetta jowl tri-tip ribeye jerky ham meatball sirloin sausage tail headcheese andouille rump salami sausage jowl short tri-tip beef bresaola pastrami ball pork headcheese tail ball boudin drumstick ham tail sausage tongue t-bone brisket andouille ball meatball chicken bresaola biltong loin bresaola pork pork rump swine chicken ground bresaola t-bone chuck ribeye shankle pancetta ham ground ribs shank cow rump bacon chuck meatball loin pork", IsComplete = "True", DueDate = DateTime.Parse("2014-05-26 00:00:00")},
                    new DataObject {Id = "29", Title = "Jowl meatball", Notes = "Cow tenderloin beef headcheese pancetta pig andouille tri-tip tail turkey bacon pancetta turkey andouille bresaola short jowl beef corned boudin tenderloin tongue salami pork pork chuck ribs shoulder t-bone fatback shank headcheese jowl salami turkey pancetta sirloin bresaola short beef bresaola sirloin swine tail corned chuck meatball beef chicken", IsComplete = "False", DueDate = DateTime.Parse("2014-06-06 00:00:00")},
                    new DataObject {Id = "30", Title = "Ham pork rump", Notes = "Ribs chicken biltong tri-tip hamburger headcheese tri-tip chicken cow chicken drumstick pork drumstick bacon short ball pork t-bone andouille ribs rump t-bone drumstick meatball ball ribeye ball headcheese ribs jowl tenderloin shoulder headcheese ground shank ball tenderloin pork corned pork short beef pork rump pig chuck pancetta pork ribs swine pork pork ball pork sirloin ribs ground pancetta", IsComplete = "False", DueDate = DateTime.Parse("2014-05-24 00:00:00")},
                    new DataObject {Id = "31", Title = "Brisket ham bacon", Notes = "Boudin brisket ball tongue pastrami shank t-bone t-bone ham sirloin sirloin hamburger ribeye pork ham fatback shank ribs biltong pastrami jerky chuck bresaola andouille biltong salami meatloaf chuck pancetta tongue cow shankle beef headcheese boudin chicken flank headcheese ribs venison tenderloin loin jowl swine beef spare boudin cow tail cow short hamburger jowl ham", IsComplete = "False", DueDate = DateTime.Parse("2014-05-29 00:00:00")},
                    new DataObject {Id = "32", Title = "Tenderloin boudin tail", Notes = "Beef venison salami jerky pancetta biltong shoulder headcheese rump beef ball chuck ribs short salami beef tenderloin tenderloin ground tail ball t-bone pancetta corned ham corned tail ham cow spare shank spare ball ball boudin bresaola pastrami shankle chicken ribs spare beef short salami pancetta corned rump pork pork cow tail corned headcheese bresaola t-bone t-bone drumstick pork ribs corned pork ham", IsComplete = "False", DueDate = DateTime.Parse("2014-05-30 00:00:00")},
                    new DataObject {Id = "33", Title = "Boudin ribeye ham", Notes = "Short sirloin chicken ball pork spare andouille meatball ribeye tail flank tongue swine t-bone corned ham meatloaf jowl pork tri-tip chicken tri-tip pork ball ball ham boudin pork shankle salami andouille chuck ribs ham pork andouille ribs t-bone sirloin biltong pancetta beef pork andouille tail hamburger", IsComplete = "False", DueDate = DateTime.Parse("2014-05-19 00:00:00")},
                    new DataObject {Id = "34", Title = "Tongue jowl sirloin", Notes = "Pork salami chicken jowl pancetta ground swine chuck bacon bacon beef salami tri-tip bresaola chicken drumstick pig bacon beef headcheese short andouille tongue headcheese short headcheese rump corned fatback headcheese pork jowl pork jowl ground boudin strip pork pork ham", IsComplete = "False", DueDate = DateTime.Parse("2014-05-28 00:00:00")},
                    new DataObject {Id = "35", Title = "Chuck beef boudin", Notes = "T-bone bresaola short venison pork headcheese corned venison corned chuck rump pastrami cow boudin pancetta shank ham bresaola pork meatball pork loin spare loin hamburger pork jerky pork ham ham pastrami pork meatball jowl ball short bacon spare boudin t-bone venison spare ham andouille turkey bacon beef pig biltong ground pancetta andouille", IsComplete = "False", DueDate = DateTime.Parse("2014-05-27 00:00:00")},
                    new DataObject {Id = "36", Title = "Cow sirloin", Notes = "Venison ham bacon spare shoulder ribs shoulder sirloin fatback chicken corned ham boudin pastrami spare boudin ham pork bacon meatball spare pork sausage jerky ball flank headcheese tongue chicken ground turkey chuck corned pork swine pig chicken cow brisket bacon boudin tongue tongue bacon spare flank", IsComplete = "True", DueDate = DateTime.Parse("2014-06-07 00:00:00")},
                    new DataObject {Id = "37", Title = "Tail bresaola rump", Notes = "Jerky brisket chuck pork bresaola ground sausage drumstick andouille tri-tip chicken fatback salami t-bone ham ribs rump pork salami tongue drumstick boudin swine ribeye short ham t-bone rump pancetta ground tenderloin loin jowl pastrami bresaola sausage tri-tip t-bone meatloaf salami ball boudin bacon bacon beef shank tail flank pancetta cow ribs ground hamburger ribs meatloaf corned ribeye chicken tongue jowl ham fatback bacon headcheese tri-tip andouille tail sirloin pig", IsComplete = "True", DueDate = DateTime.Parse("2014-06-02 00:00:00")},
                    new DataObject {Id = "38", Title = "T-bone pig pancetta", Notes = "Spare shoulder jowl ground t-bone corned headcheese hamburger sirloin biltong chuck boudin ball salami tri-tip salami meatloaf loin pancetta beef t-bone headcheese cow fatback chuck tongue ground meatloaf jowl chuck spare ground ground pork meatball meatloaf ground t-bone headcheese venison chicken beef ribs bacon tail salami tongue pork pork rump turkey", IsComplete = "True", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "39", Title = "Flank biltong", Notes = "T-bone pancetta pork tenderloin short bacon beef drumstick chuck tri-tip loin brisket short ribs ribs ribs t-bone hamburger sausage beef meatloaf ribs ball tri-tip short short beef spare strip ball bresaola ground brisket spare sausage meatloaf venison beef rump ham t-bone bresaola jerky", IsComplete = "False", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "40", Title = "Ball rump rump", Notes = "Ribs venison bresaola chuck t-bone tri-tip ground ribs shankle short headcheese spare rump andouille flank meatloaf flank pastrami corned chicken headcheese bresaola tail chicken bresaola spare hamburger sirloin cow venison jowl spare short strip andouille chicken salami sausage spare tenderloin ribs bresaola pork", IsComplete = "False", DueDate = DateTime.Parse("2014-05-19 00:00:00")},
                    new DataObject {Id = "41", Title = "Ribs pork", Notes = "Tail ribeye boudin ribeye short bacon chuck chuck ball headcheese salami tenderloin ground tenderloin tail tenderloin strip sirloin tail jowl meatball loin drumstick swine chicken short ham biltong tongue drumstick headcheese jerky tail corned ham jowl tenderloin brisket andouille chuck rump ribs meatloaf jowl pig t-bone sirloin pork salami ground pork ribs short beef swine shoulder", IsComplete = "True", DueDate = DateTime.Parse("2014-05-15 00:00:00")},
                    new DataObject {Id = "42", Title = "Meatball tri-tip chicken", Notes = "Boudin tenderloin turkey drumstick sausage beef corned turkey pancetta ribs rump pancetta sausage sirloin chicken ball pancetta t-bone headcheese biltong pork tenderloin tenderloin sirloin swine beef rump chuck pork meatloaf pork beef ham shank jowl andouille strip pork tenderloin tri-tip t-bone corned flank ground pork chuck tri-tip pancetta sirloin pork tail chuck rump tongue venison venison salami pork", IsComplete = "True", DueDate = DateTime.Parse("2014-05-24 00:00:00")},
                    new DataObject {Id = "43", Title = "Bresaola short", Notes = "Jerky shankle shankle salami tri-tip ham bresaola shoulder shank chicken ham biltong salami strip biltong t-bone salami headcheese short pork meatloaf meatloaf pork meatloaf tail tenderloin corned ball biltong brisket cow tri-tip sirloin salami sirloin boudin bacon shank chuck tri-tip strip jerky corned drumstick drumstick headcheese pig ham shankle ball headcheese turkey ball pork headcheese chuck tail", IsComplete = "True", DueDate = DateTime.Parse("2014-05-22 00:00:00")},
                    new DataObject {Id = "44", Title = "Hamburger drumstick", Notes = "Cow bresaola pork tail sirloin pancetta sausage bacon bresaola turkey brisket drumstick tenderloin chicken ribs beef tri-tip pork boudin rump chuck tongue chicken bacon ball pig loin headcheese bacon turkey spare meatloaf short corned jowl brisket ribeye corned venison shank pork shank ball andouille meatloaf salami tri-tip t-bone corned jowl jowl beef sirloin ribeye sirloin short boudin ribs t-bone corned spare spare tri-tip tenderloin fatback ham rump", IsComplete = "False", DueDate = DateTime.Parse("2014-06-02 00:00:00")},
                    new DataObject {Id = "45", Title = "Sirloin ham venison", Notes = "Spare cow boudin pastrami fatback salami pancetta pig chicken shank cow bacon sausage ribeye tail headcheese bresaola bresaola tri-tip ground biltong meatball pork chicken loin short t-bone fatback pork shankle chicken t-bone salami pancetta pancetta fatback ball ground ham sirloin pancetta pig chicken tongue pork strip ribeye tenderloin t-bone pancetta tail", IsComplete = "True", DueDate = DateTime.Parse("2014-06-04 00:00:00")},
                    new DataObject {Id = "46", Title = "Boudin ball", Notes = "Venison jowl chicken bacon shank headcheese beef t-bone ribs tenderloin jowl drumstick meatball rump ball ribs tri-tip tail flank sirloin t-bone beef drumstick bresaola loin chuck fatback ground shankle venison t-bone jowl cow salami pig ball chuck sirloin ham ball pork strip ground jowl pork chicken corned sausage beef chicken ribeye drumstick boudin chuck ball pork beef strip venison chicken cow fatback", IsComplete = "False", DueDate = DateTime.Parse("2014-05-18 00:00:00")},
                    new DataObject {Id = "47", Title = "Flank shank", Notes = "Corned swine chicken ball pastrami t-bone boudin chicken drumstick bresaola venison corned tenderloin ground ribeye short ground jowl fatback pork bacon andouille ball flank spare corned short t-bone headcheese t-bone tail short t-bone flank ground flank ball chicken flank chuck beef pancetta ham pork corned ham jerky headcheese ball ball strip t-bone", IsComplete = "True", DueDate = DateTime.Parse("2014-05-25 00:00:00")},
                    new DataObject {Id = "48", Title = "Pork corned tongue", Notes = "Flank boudin brisket boudin tri-tip ham tenderloin tenderloin short chuck bresaola brisket venison ball bresaola tongue ribs chicken tenderloin ground ham swine tenderloin strip tri-tip pork rump bresaola tail jowl ham hamburger headcheese bresaola boudin beef t-bone pork fatback fatback bacon ground ball shank spare tail sausage ball tongue pastrami", IsComplete = "True", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "49", Title = "Tenderloin tri-tip pancetta", Notes = "Shankle salami salami headcheese sirloin tail chuck t-bone ribeye t-bone ribs t-bone boudin chicken shank pastrami jerky tenderloin spare biltong short sausage ball pork beef tri-tip ribeye short cow tenderloin flank chuck corned chuck pork tail short tail pig boudin chuck jerky tail tail sausage", IsComplete = "False", DueDate = DateTime.Parse("2014-05-27 00:00:00")},
                    new DataObject {Id = "50", Title = "Chuck ham", Notes = "Chuck fatback beef flank boudin hamburger ground andouille loin boudin cow t-bone sirloin ribeye andouille t-bone short short pancetta chicken biltong chicken bresaola shankle pork ham hamburger andouille tri-tip turkey chuck boudin boudin headcheese shoulder flank sausage chicken headcheese beef pork pork tenderloin t-bone corned bacon strip spare meatloaf turkey meatloaf cow ribeye tenderloin t-bone ham beef fatback brisket meatball turkey chicken", IsComplete = "False", DueDate = DateTime.Parse("2014-05-18 00:00:00")},
                    new DataObject {Id = "51", Title = "Strip beef", Notes = "Bacon chicken bacon boudin ribs brisket jowl jerky meatloaf ham bresaola brisket chicken short pastrami ribeye chicken ham fatback hamburger ham corned shank shank meatloaf drumstick pork ground corned pork beef meatball turkey bacon spare headcheese tail short pastrami tail pastrami ball boudin pig cow fatback ham t-bone", IsComplete = "True", DueDate = DateTime.Parse("2014-06-07 00:00:00")},
                    new DataObject {Id = "52", Title = "Shank drumstick", Notes = "Chicken headcheese shank bresaola headcheese ground andouille salami flank spare ribeye ground bacon ribeye pancetta sirloin jerky jerky brisket shankle pork pork bresaola pork pork ground beef pig hamburger boudin loin biltong short shank tail pork t-bone bacon tongue corned bresaola short shoulder ground brisket salami bacon ribs spare shoulder cow tri-tip short pork tri-tip flank short", IsComplete = "False", DueDate = DateTime.Parse("2014-05-29 00:00:00")},
                    new DataObject {Id = "53", Title = "Pork spare fatback", Notes = "Meatball pork boudin headcheese tail tail ribs pig pork turkey jerky boudin sirloin cow bresaola pork tenderloin swine rump andouille andouille brisket drumstick chuck fatback venison corned pork jerky pig pancetta chicken pancetta fatback spare corned tongue boudin shankle tenderloin beef chicken corned hamburger tri-tip headcheese t-bone rump pork ground", IsComplete = "False", DueDate = DateTime.Parse("2014-05-19 00:00:00")},
                    new DataObject {Id = "54", Title = "Boudin strip", Notes = "Ham chuck venison pastrami salami ham meatloaf t-bone fatback tenderloin jowl pork fatback shoulder shank pork hamburger chuck headcheese tongue pancetta jowl hamburger brisket chuck pastrami ham venison pig brisket tongue pancetta shank sirloin shankle beef andouille chuck meatball tri-tip short venison chuck andouille pancetta venison ham venison boudin boudin bacon cow bresaola pork shank ribeye pancetta corned t-bone pork ribs", IsComplete = "False", DueDate = DateTime.Parse("2014-05-26 00:00:00")},
                    new DataObject {Id = "55", Title = "Flank andouille", Notes = "Bresaola sirloin t-bone meatloaf boudin beef pig biltong short pork meatloaf jowl shoulder salami tenderloin pig biltong turkey jerky loin beef boudin pig short venison chuck andouille short loin ribs chicken biltong pork t-bone andouille tenderloin jowl drumstick short pig chicken chuck shoulder ribeye beef swine pork ball pig t-bone bresaola pancetta shankle drumstick beef chuck headcheese t-bone", IsComplete = "True", DueDate = DateTime.Parse("2014-05-19 00:00:00")},
                    new DataObject {Id = "56", Title = "Drumstick headcheese pig", Notes = "Headcheese rump loin bacon andouille beef ground shank bresaola meatball ribeye corned spare bacon turkey cow salami beef tenderloin pork shank venison headcheese t-bone turkey meatball cow ball shoulder chuck pancetta pig ground fatback pancetta pastrami bacon spare bresaola short brisket tail andouille hamburger brisket fatback biltong turkey chuck pork corned beef sirloin andouille", IsComplete = "False", DueDate = DateTime.Parse("2014-06-02 00:00:00")},
                    new DataObject {Id = "57", Title = "Jowl ribeye spare", Notes = "Venison tenderloin salami short andouille brisket ball andouille andouille pig tail biltong flank t-bone chicken t-bone drumstick salami andouille drumstick pastrami ground meatball drumstick spare boudin ground andouille venison pig chuck short pig ball pork shankle chuck pig pork pig t-bone", IsComplete = "False", DueDate = DateTime.Parse("2014-05-16 00:00:00")},
                    new DataObject {Id = "58", Title = "T-bone short ham", Notes = "Tongue beef boudin corned ball t-bone fatback ribeye tenderloin chicken andouille hamburger biltong beef chicken salami ground beef pork pig ribeye ribs drumstick t-bone cow meatball pork headcheese pork chicken biltong boudin turkey venison ribeye meatball tenderloin ball corned sirloin beef andouille biltong venison pancetta fatback boudin flank loin drumstick andouille chicken drumstick ground spare pastrami short tail meatloaf pastrami tri-tip shank ribeye pig", IsComplete = "False", DueDate = DateTime.Parse("2014-06-07 00:00:00")},
                    new DataObject {Id = "59", Title = "Bresaola chuck", Notes = "Pig venison sausage tenderloin chicken meatball short tri-tip hamburger pork pastrami venison shank cow chicken pork pork boudin tail chuck pastrami chicken salami jerky spare pork ground ribeye sirloin pork headcheese ribs ribeye short chicken corned beef short ball andouille fatback beef swine pork flank bacon loin boudin short jowl headcheese turkey beef spare pork boudin bresaola bacon ground pig chicken", IsComplete = "True", DueDate = DateTime.Parse("2014-06-03 00:00:00")},
                    new DataObject {Id = "60", Title = "Chicken pork", Notes = "Biltong meatball spare fatback sausage jowl pig t-bone beef tongue shankle short jowl pancetta boudin beef cow ribs chuck swine sirloin spare ham short headcheese ham boudin venison biltong meatloaf ground cow tri-tip chuck headcheese pork ground spare turkey sirloin pig swine ribeye flank", IsComplete = "True", DueDate = DateTime.Parse("2014-06-03 00:00:00")},
                    new DataObject {Id = "61", Title = "Shank ham loin", Notes = "Beef beef cow meatloaf ground chuck pancetta andouille ground pork ham ground chuck pork jowl swine shank ground beef salami short short bresaola brisket ham shank corned ribeye andouille tenderloin spare beef tri-tip bacon short bresaola ham ham pork venison ham bresaola ribs", IsComplete = "True", DueDate = DateTime.Parse("2014-05-29 00:00:00")},
                    new DataObject {Id = "62", Title = "Tri-tip short", Notes = "Salami sirloin beef chuck boudin hamburger chuck ball pork jerky spare pancetta t-bone chicken bacon jerky ribs sausage t-bone ground ham fatback t-bone ground drumstick flank tongue jowl tongue corned spare short headcheese venison pork beef flank shank chuck pork venison sirloin corned brisket cow chicken ham salami short andouille ham ribeye ground chicken pork chicken rump salami ribeye meatball beef beef tongue", IsComplete = "False", DueDate = DateTime.Parse("2014-05-19 00:00:00")},
                    new DataObject {Id = "63", Title = "Pancetta ground", Notes = "Boudin tenderloin strip bresaola biltong chuck headcheese pork cow sausage ham tri-tip ham ribs t-bone pancetta cow tri-tip chicken pork corned pork cow meatball headcheese shank beef shank jowl boudin tail pig chicken ham fatback turkey chicken hamburger chicken beef tongue ribs beef ribs biltong venison shoulder pig pork venison ribs ribeye flank tail salami headcheese venison venison boudin beef headcheese boudin pork", IsComplete = "False", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "64", Title = "Short tongue", Notes = "Tri-tip bresaola bresaola chuck chicken spare loin venison tenderloin boudin shank beef meatball ground beef rump t-bone pancetta pancetta headcheese beef t-bone boudin pancetta brisket cow biltong rump pancetta corned ribs venison strip boudin corned pancetta short drumstick t-bone andouille chicken shank tongue beef", IsComplete = "False", DueDate = DateTime.Parse("2014-05-29 00:00:00")},
                    new DataObject {Id = "65", Title = "Ribs meatloaf pancetta", Notes = "Loin flank t-bone sirloin pancetta turkey shank ham ball chicken corned cow shank ground shank pork pastrami short rump ribs meatloaf t-bone pork pork pancetta sirloin rump jowl brisket beef spare t-bone pig ribs drumstick shoulder ribeye chicken flank meatball shoulder pig ball pancetta flank fatback cow ground sausage tri-tip venison ribeye jowl ribeye shank ham strip tail tri-tip sirloin spare jowl headcheese ball sirloin tail", IsComplete = "False", DueDate = DateTime.Parse("2014-05-26 00:00:00")},
                    new DataObject {Id = "66", Title = "Pig ham", Notes = "Brisket tenderloin pork tri-tip tail tenderloin chuck fatback tenderloin headcheese ball jowl spare drumstick ground venison pork sirloin t-bone meatball biltong short strip ground pancetta spare andouille tri-tip ground meatball andouille pork shankle rump andouille rump headcheese sirloin beef ham andouille bresaola andouille andouille tenderloin sirloin pork tail sirloin jerky pancetta chicken headcheese beef sirloin", IsComplete = "True", DueDate = DateTime.Parse("2014-06-08 00:00:00")},
                    new DataObject {Id = "67", Title = "Pork ribeye", Notes = "Pork ham fatback boudin shankle bresaola biltong ball cow tenderloin jerky tail ground shoulder biltong t-bone ground ribs pastrami ball pork venison ham biltong sirloin brisket bacon headcheese fatback chicken shank pancetta tri-tip bacon beef ham fatback meatball salami ribeye tenderloin sirloin sausage beef pancetta andouille andouille", IsComplete = "False", DueDate = DateTime.Parse("2014-05-28 00:00:00")},
                    new DataObject {Id = "68", Title = "Beef brisket biltong", Notes = "Brisket chicken short sausage meatloaf jowl beef pork turkey beef tail pig andouille rump ribs chicken headcheese ground pork spare pig hamburger ham ham bresaola andouille andouille boudin meatloaf venison tongue andouille tail fatback salami headcheese drumstick venison andouille tail andouille hamburger tri-tip turkey chicken pork corned ribs bresaola", IsComplete = "False", DueDate = DateTime.Parse("2014-05-22 00:00:00")},
                    new DataObject {Id = "69", Title = "Beef tri-tip jowl", Notes = "Meatloaf pork chuck brisket short bacon venison ball ham salami headcheese loin chicken ground jowl cow turkey sirloin ball andouille corned headcheese boudin shank headcheese t-bone fatback salami tenderloin sirloin ground pancetta pork ground shoulder beef ham boudin biltong cow beef turkey ham rump pork ribeye tenderloin sausage fatback ball t-bone ribs tri-tip ground ball ham ribeye tongue bacon drumstick hamburger drumstick corned venison salami tail flank", IsComplete = "False", DueDate = DateTime.Parse("2014-06-04 00:00:00")},
                    new DataObject {Id = "70", Title = "Pork turkey headcheese", Notes = "Chicken short tenderloin corned pancetta strip corned ribs strip sausage pork t-bone shankle tail ham pork flank short pancetta chuck ribeye short venison chicken ball headcheese short venison short t-bone biltong jowl fatback short pancetta t-bone meatloaf ground beef fatback ribs fatback ham bresaola t-bone shoulder jowl headcheese bacon chicken salami short tongue tenderloin pastrami ribs biltong headcheese ribs t-bone shankle corned ground turkey short", IsComplete = "True", DueDate = DateTime.Parse("2014-06-04 00:00:00")},
                    new DataObject {Id = "71", Title = "Tri-tip pork", Notes = "Corned tongue ham bresaola shankle biltong pork ribeye short hamburger pork headcheese bacon biltong turkey ball salami spare rump pork corned drumstick flank boudin beef chicken pastrami jowl tenderloin short ball biltong meatball ball sausage ribs rump short andouille chuck chuck chicken short jowl shankle meatball chuck", IsComplete = "True", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "72", Title = "Pork pork tail", Notes = "T-bone chuck bacon boudin venison ball salami pork ribeye tri-tip pancetta shoulder bacon shank beef rump boudin flank t-bone tenderloin shank meatloaf ball pork meatball ribs sirloin pig tongue fatback boudin fatback fatback ribeye jowl ham bresaola shoulder ribeye spare tri-tip sirloin pork venison tri-tip salami sirloin turkey salami jowl pork shank", IsComplete = "True", DueDate = DateTime.Parse("2014-06-05 00:00:00")},
                    new DataObject {Id = "73", Title = "Ham corned spare", Notes = "Turkey bresaola venison chicken pork headcheese beef pork shankle swine ham ham jerky corned ham andouille jowl sirloin chuck pork pancetta pork pork short meatball sausage ribeye cow chuck meatloaf pork jowl ribs drumstick short rump shank pork t-bone fatback pork boudin venison beef", IsComplete = "True", DueDate = DateTime.Parse("2014-05-20 00:00:00")},
                    new DataObject {Id = "74", Title = "Chuck beef ball", Notes = "Shank ribs sausage shoulder ribeye fatback sirloin sausage flank tail sirloin andouille tri-tip tongue tail pancetta strip ribs jowl drumstick sirloin ribeye strip jerky swine shank boudin corned chuck ham shank headcheese headcheese venison andouille bacon andouille beef tenderloin shoulder tail beef beef tenderloin swine", IsComplete = "True", DueDate = DateTime.Parse("2014-05-22 00:00:00")},
                    new DataObject {Id = "75", Title = "Fatback pork", Notes = "Pork tenderloin biltong boudin t-bone chicken ribeye tri-tip tri-tip pig tenderloin headcheese shank corned ground tri-tip fatback brisket fatback pork jowl tenderloin tail jerky boudin beef pancetta tail short boudin chuck brisket pork pork meatloaf pork drumstick pork venison short headcheese tail ham pancetta bresaola sirloin bacon pancetta corned short ball pork shankle headcheese drumstick meatloaf salami short", IsComplete = "False", DueDate = DateTime.Parse("2014-06-06 00:00:00")},
                    new DataObject {Id = "76", Title = "Tail pork brisket", Notes = "Brisket ribs corned tenderloin t-bone meatball salami spare meatloaf pancetta tenderloin fatback sausage sirloin short fatback chicken bresaola spare ball salami brisket beef corned meatloaf rump pastrami rump ham sirloin tongue tail short t-bone ham venison t-bone venison andouille drumstick", IsComplete = "False", DueDate = DateTime.Parse("2014-06-03 00:00:00")},
                    new DataObject {Id = "77", Title = "Meatloaf shank", Notes = "Meatball drumstick meatloaf ground tenderloin strip sausage beef ribs pancetta chuck ribs chuck sirloin ribeye andouille ham beef boudin fatback ham shank flank tail tri-tip pork sausage ball ham pork pancetta pig pastrami drumstick boudin boudin sausage pastrami boudin chicken pork pancetta shank ham tongue bresaola cow venison corned biltong pork pork t-bone pancetta pork chuck tri-tip corned strip bresaola tenderloin andouille flank", IsComplete = "True", DueDate = DateTime.Parse("2014-05-18 00:00:00")},
                    new DataObject {Id = "78", Title = "Rump pork rump", Notes = "Chicken biltong chicken jowl cow corned chicken turkey corned tongue bresaola spare shank ball t-bone jowl bacon ham shank bacon pig jowl andouille beef pancetta pork t-bone shankle bresaola drumstick drumstick boudin t-bone shank tail tri-tip corned boudin rump cow chicken tri-tip bacon short tri-tip pork pig jerky bacon andouille pork", IsComplete = "True", DueDate = DateTime.Parse("2014-06-08 00:00:00")},
                    new DataObject {Id = "79", Title = "Sirloin pig", Notes = "Ground andouille boudin venison pork tenderloin pancetta chuck flank tongue ground boudin headcheese short turkey ground ribeye ball loin hamburger bacon ham tenderloin andouille tri-tip pork t-bone beef loin turkey ham ham rump chuck beef ribeye bresaola shank bacon venison t-bone sausage pancetta boudin pastrami sausage t-bone sirloin meatloaf cow pork beef chuck drumstick headcheese", IsComplete = "False", DueDate = DateTime.Parse("2014-06-06 00:00:00")},
                    new DataObject {Id = "80", Title = "Flank strip sirloin", Notes = "Short brisket salami tri-tip jerky turkey tongue tongue jerky ribeye andouille tongue pork spare boudin chuck ground t-bone venison biltong tongue hamburger spare brisket ham andouille fatback ham spare headcheese jerky bacon chicken pastrami ribeye venison ribs spare spare venison ground", IsComplete = "False", DueDate = DateTime.Parse("2014-05-31 00:00:00")},
                    new DataObject {Id = "81", Title = "Tongue hamburger", Notes = "Bresaola venison boudin tri-tip ribs chicken pork ham drumstick pig chuck ham bacon beef short pork t-bone ribs shoulder pork cow pork andouille hamburger turkey chuck bacon bacon boudin cow tail chicken beef ham headcheese short ribeye sausage cow ham headcheese chuck beef drumstick biltong pork biltong pancetta tri-tip", IsComplete = "False", DueDate = DateTime.Parse("2014-06-04 00:00:00")},
                    new DataObject {Id = "82", Title = "Ribs flank", Notes = "Sirloin sirloin meatloaf chicken loin sirloin shank bresaola spare ball tri-tip jowl flank boudin pork fatback drumstick salami rump pancetta tongue tongue ribeye bacon chuck pork turkey ball t-bone salami jowl sirloin biltong bresaola ham boudin turkey sausage fatback swine tri-tip andouille t-bone", IsComplete = "False", DueDate = DateTime.Parse("2014-06-02 00:00:00")},
                    new DataObject {Id = "83", Title = "Headcheese pork", Notes = "T-bone spare chuck chuck ham pork chuck bresaola boudin tenderloin flank boudin rump salami beef bacon sirloin ham tail turkey shankle fatback cow venison andouille chicken spare fatback jowl loin ribeye jowl bacon shoulder pig pastrami headcheese turkey sirloin bacon", IsComplete = "True", DueDate = DateTime.Parse("2014-05-21 00:00:00")},
                    new DataObject {Id = "84", Title = "Biltong t-bone", Notes = "Corned t-bone pig brisket chicken ground sausage bresaola ribs meatball flank andouille spare tongue sirloin meatball bresaola bresaola bacon cow fatback ham tenderloin ball tail short shankle jowl beef ground jowl ground boudin spare loin meatloaf shankle pork meatloaf meatloaf tenderloin fatback bresaola pastrami ham ball pastrami meatball t-bone turkey shank fatback andouille chuck brisket shoulder tail boudin short sausage tenderloin", IsComplete = "False", DueDate = DateTime.Parse("2014-05-25 00:00:00")},
                    new DataObject {Id = "85", Title = "Chicken headcheese", Notes = "Fatback t-bone corned ground sirloin pancetta ribs spare andouille tenderloin chicken cow tri-tip spare chicken venison chuck pork tongue loin t-bone t-bone ham chuck tenderloin chuck sirloin pancetta ham ribs headcheese pig andouille ham boudin chicken t-bone fatback ground chicken bresaola chicken shoulder jowl cow", IsComplete = "False", DueDate = DateTime.Parse("2014-06-08 00:00:00")},
                    new DataObject {Id = "86", Title = "Tongue turkey sirloin", Notes = "Spare tenderloin pork ball corned turkey chicken tenderloin jerky t-bone corned ham short strip flank boudin tenderloin salami chuck tongue boudin fatback turkey headcheese loin tongue ground tongue beef salami tenderloin bresaola salami bresaola sirloin pig beef boudin andouille tail tenderloin t-bone tri-tip venison chuck beef bresaola headcheese pork pork andouille beef chicken sirloin brisket beef headcheese cow turkey venison sirloin", IsComplete = "False", DueDate = DateTime.Parse("2014-05-18 00:00:00")},
                    new DataObject {Id = "87", Title = "Rump drumstick", Notes = "Chicken spare ground t-bone ribeye shank ribs pancetta corned jerky tail ham tri-tip tongue andouille rump bresaola spare fatback beef pork fatback pork salami ground ribeye ham ham sausage chicken short chicken short t-bone loin ground pig tongue beef andouille bacon rump headcheese strip andouille sausage meatball spare venison brisket tenderloin flank headcheese cow t-bone bacon pig flank sirloin headcheese tongue meatball flank meatloaf bresaola bresaola bacon ribs tenderloin", IsComplete = "True", DueDate = DateTime.Parse("2014-05-22 00:00:00")},
                    new DataObject {Id = "88", Title = "Short venison", Notes = "Pork beef spare ham pastrami sirloin beef loin hamburger andouille pork andouille sausage jerky jowl ribeye ribeye t-bone shoulder jowl bacon ball flank tri-tip ball chicken rump chicken tri-tip bresaola t-bone flank chicken rump ham cow pig andouille pancetta chuck ham ham shank ribeye ribs pancetta t-bone meatloaf rump tri-tip jowl pig t-bone pig loin chuck brisket drumstick pancetta ham boudin", IsComplete = "True", DueDate = DateTime.Parse("2014-05-17 00:00:00")},
                    new DataObject {Id = "89", Title = "Shank tail", Notes = "Andouille spare drumstick shankle t-bone boudin headcheese tail cow ribs meatball chicken t-bone boudin pancetta t-bone pork shoulder ham tail pig pork pig chicken cow pancetta ground hamburger headcheese chuck andouille venison shank tenderloin boudin ribeye tenderloin short tenderloin tongue shoulder ham chuck tri-tip flank flank ball tenderloin bresaola boudin tongue cow meatloaf short ham cow t-bone chicken jowl pancetta tri-tip biltong beef spare corned", IsComplete = "False", DueDate = DateTime.Parse("2014-05-22 00:00:00")},
                    new DataObject {Id = "90", Title = "Ribs t-bone bacon", Notes = "Tongue pork hamburger strip tenderloin chuck ham sausage short beef bresaola ribeye brisket ball boudin pork chuck flank flank tenderloin brisket short chicken chicken short chicken ribeye beef t-bone beef hamburger pig chuck hamburger pig pig boudin tenderloin bacon bresaola ribs tenderloin meatball sausage chicken ham beef bacon shankle venison", IsComplete = "False", DueDate = DateTime.Parse("2014-05-22 00:00:00")},
                    new DataObject {Id = "91", Title = "Beef salami", Notes = "Venison pork andouille pork shank turkey tri-tip chuck headcheese ham pork pork tail t-bone t-bone ball ham meatball chicken chicken tri-tip pork sirloin chicken shoulder boudin venison tail beef ham pancetta turkey shank jowl pork ham headcheese salami beef tri-tip beef spare pancetta salami", IsComplete = "True", DueDate = DateTime.Parse("2014-06-03 00:00:00")},
                    new DataObject {Id = "92", Title = "Headcheese drumstick chicken", Notes = "T-bone tail short flank ribs sirloin corned bacon fatback pork cow turkey tenderloin sirloin tail bacon pork cow ground drumstick ground cow ribs pork shank drumstick fatback pork beef pastrami ham chuck pork tenderloin ham sausage venison headcheese ground bresaola t-bone meatball tongue ham venison hamburger boudin bresaola chicken flank swine ribs pork", IsComplete = "True", DueDate = DateTime.Parse("2014-05-29 00:00:00")},
                    new DataObject {Id = "93", Title = "Fatback shank", Notes = "Pork ribs fatback chuck venison pancetta pork flank pancetta andouille ball pastrami boudin spare beef ground ground turkey ball meatloaf meatloaf pork strip boudin sirloin jowl pancetta bacon ball ribeye turkey boudin ground shank flank loin headcheese biltong beef shank pastrami bresaola ribeye spare pastrami bacon sirloin tenderloin hamburger corned beef strip chuck beef ribs chicken t-bone tenderloin", IsComplete = "True", DueDate = DateTime.Parse("2014-05-24 00:00:00")},
                    new DataObject {Id = "94", Title = "Ribeye strip strip", Notes = "Ball beef pastrami chicken ham sirloin pancetta andouille chicken tenderloin chuck ball jowl ham tail jowl tail andouille bacon chuck jowl rump shankle pork ball beef ball bresaola shank tail bacon t-bone shoulder cow turkey ham beef t-bone shankle tri-tip andouille t-bone brisket ham ribeye brisket", IsComplete = "False", DueDate = DateTime.Parse("2014-05-31 00:00:00")},
                    new DataObject {Id = "95", Title = "Pancetta tri-tip", Notes = "Beef cow pork biltong pork short ham pastrami pastrami pork ham drumstick t-bone ribs jowl fatback bresaola ham salami andouille ribeye ball boudin drumstick headcheese meatball venison ground t-bone t-bone pork ham pork tenderloin beef turkey short cow tenderloin biltong pastrami headcheese short headcheese short ball ham headcheese flank beef fatback pancetta chuck jowl pastrami bacon beef pork spare hamburger tongue shoulder strip cow pancetta beef jowl", IsComplete = "False", DueDate = DateTime.Parse("2014-05-24 00:00:00")},
                    new DataObject {Id = "96", Title = "Beef brisket", Notes = "T-bone salami ribeye sirloin salami rump bresaola beef pork tenderloin pig biltong bacon sirloin ribeye cow pig pancetta ribs ham turkey sausage venison pig brisket beef pork t-bone flank beef flank venison ball fatback t-bone biltong jowl andouille beef chicken corned chuck rump boudin ham", IsComplete = "False", DueDate = DateTime.Parse("2014-05-29 00:00:00")},
                    new DataObject {Id = "97", Title = "Ground tongue", Notes = "Turkey chuck meatball meatloaf jowl pancetta pork flank chuck pastrami turkey salami bresaola shank bacon boudin tenderloin pancetta ham ribeye tongue tail venison spare andouille pork beef pork bresaola meatball meatloaf venison pancetta biltong bacon shankle shoulder tongue tail tongue boudin short headcheese andouille spare boudin bacon beef beef venison cow flank tenderloin spare tongue", IsComplete = "True", DueDate = DateTime.Parse("2014-05-27 00:00:00")},
                    new DataObject {Id = "98", Title = "T-bone short", Notes = "Sausage short ham shankle headcheese jowl ribs shankle pancetta chuck ribs jowl boudin pig shoulder salami andouille headcheese ball ball pig tongue boudin pork venison sirloin pastrami sirloin ribeye shankle tenderloin pancetta tail ball beef andouille sirloin tri-tip flank shank t-bone short fatback andouille bacon spare tail short ribeye venison corned loin boudin tail ribeye ham andouille salami headcheese pork boudin ground salami short ribs corned", IsComplete = "False", DueDate = DateTime.Parse("2014-06-01 00:00:00")},
                    new DataObject {Id = "99", Title = "T-bone tri-tip spare", Notes = "Ribeye drumstick corned flank shank meatball boudin pastrami strip meatloaf hamburger chuck turkey headcheese spare tail shank hamburger ball chicken andouille boudin short ribeye t-bone drumstick bacon tri-tip pork cow sirloin chuck spare chuck meatloaf headcheese salami boudin t-bone andouille headcheese jerky shoulder", IsComplete = "True", DueDate = DateTime.Parse("2014-05-24 00:00:00")},
                };
        }
    }
}
